[package]
name = "halo-infra"
version = "0.1.5"
edition = "2024"
description = "halo core（配置/服务基础能力）"
license = "Apache-2.0"
repository = "https://github.com/halo-space/halo.git"
readme = "../README.md"

[lib]
name = "infra"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
toml = "0.8"
tokio = { version = "1", features = ["sync", "macros", "rt", "rt-multi-thread", "time"], optional = false }
parking_lot = "0.12"
redis = { version = "1", default-features = false, features = ["tokio-comp", "tokio-rustls-comp", "cluster", "connection-manager", "r2d2", "tls-rustls"] }
r2d2 = "0.8"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-util = { version = "0.7", features = ["full"] }
criterion = "0.5"
num_cpus = "1"
rustc_version_runtime = "0.1"

[[bench]]
name = "cancel_bench"
harness = false

[[bench]]
name = "deadline_bench"
harness = false

[[bench]]
name = "value_bench"
harness = false

[[bench]]
name = "done_bench"
harness = false

[[bench]]
name = "afterfunc_bench"
harness = false

[[bench]]
name = "contextaware_bench"
harness = false

[[bench]]
name = "without_cancel_bench"
harness = false

[[bench]]
name = "singleflight_bench"
harness = false

[[bench]]
name = "env_info"
harness = false


