[package]
name = "halo-core"
version = "0.1.5"
edition = "2024"
description = "halo core（配置/服务基础能力）"
license = "Apache-2.0"
repository = "https://github.com/halo-space/halo.git"
readme = "../README.md"

[lib]
# 注意：本项目选择直接使用 crate 名 `core`。
# 这样在其它 crate 中可以通过 `core::...` 引用本项目的 core。
# 如需访问标准库对应能力，优先使用 `std::...`，必要时在本 crate 内做封装。
name = "core"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
toml = "0.8"
tokio = { version = "1", features = ["sync", "macros", "rt", "rt-multi-thread", "time"], optional = false }
parking_lot = "0.12"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tokio-util = { version = "0.7", features = ["full"] }
criterion = "0.5"
num_cpus = "1"
rustc_version_runtime = "0.1"

[[bench]]
name = "cancel_bench"
harness = false

[[bench]]
name = "deadline_bench"
harness = false

[[bench]]
name = "value_bench"
harness = false

[[bench]]
name = "done_bench"
harness = false

[[bench]]
name = "afterfunc_bench"
harness = false

[[bench]]
name = "contextaware_bench"
harness = false

[[bench]]
name = "without_cancel_bench"
harness = false

[[bench]]
name = "singleflight_bench"
harness = false

[[bench]]
name = "env_info"
harness = false


