// Code generated by rsctl. DO NOT EDIT.
// rsctl {{ version }}

use std::sync::Arc;

use halo::rest::{Route, Server};
use http::Method;

use crate::svc::ServiceContext;
{%- if imports %}
{{ imports }}
{%- endif %}

pub fn register_routes(server: &mut Server, ctx: Arc<ServiceContext>) -> anyhow::Result<()> {
    server.with_root_prefix("{{ rootPrefix }}");
{{ routesAdditions }}
    Ok(())
}
