[package]
# crates.io package name
name = "halo-micro"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "halo facade crate（对外统一入口：halo_micro::core / halo_micro::rest）"

[lib]
# Facade crate name
name = "halo_micro"
path = "lib.rs"

[features]
default = []

[dependencies]
infra = { package = "halo-infra", version = "0.1.0", path = "../infra" }
rest = { package = "halo-rest", version = "0.1.0", path = "../rest" }


