[package]
name = "halo-rest"
version = "0.1.0"
edition = "2024"
description = "halo rest (web glue layer / middleware / routing DSL)"
license = "Apache-2.0"
repository = "https://github.com/halo-space/halo.git"
readme = "README.md"

[lib]
name = "rest"

[features]
default = []

[dependencies]
anyhow = "1"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
matchit = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
form_urlencoded = "1"
jsonwebtoken = "9"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
flate2 = "1"
tokio-util = "0.7"

core = { package = "halo-core", version = "0.1.0", path = "../core" }
macros = { package = "halo-macros", version = "0.1.0", path = "../macros" }

tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
criterion = { version = "0.5", features = ["async_tokio"] }
axum = { version = "0.7", features = ["macros", "json"] }


